from numpy import*
a=array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a)
print("0th row & all columns")
print(a[0,:])
print("1st row & all columns")
print(a[1,:])
print("2nd row & all columns")
print(a[2,:])
print(" 0th columns & all rows")
print(a[:,0])
print(" 1st columns & all rows")
print(a[:,1])
print(" 2nd columns & all rows")
print(a[:,2])
print(" 3rd columns & all rows")
print(a[:,3])
print(" 4th columns & all rows")
print(a[:,4])
