''' When we write lambda function inside another lambda function that is called nested lambda function.'''
s=lambda x:(lambda y=5:(x+y))
a=s(10)
print(a)
print(a(20))
print()
p=lambda m=10:(lambda n:(m+n,m*n))
t=p()
print(t)
a,m=t(20)
print("Addition",a)
print("Multiplication",m)
print("Passing lamda function to another function")
def disp(sh):
    print("Disp function")
    print(sh(8))
disp(lambda y:y)
print("We can return lambda function from function")
def add():
    print("Addition function")
    l=lambda min,max:(min+max,min-max)
    return(l)
j=add()
addition,substraction =j(min=10,max=100)
print("Addition",addition)
print("Substraction",substraction)