'''Syntax:- ("Replacement field".format(values))
R.F.={index\key:[fill][align][sign][#][0][width][,][.precision]type}'''
str="My name is{}"
print(str.format(" Prakash"))
str="My age is {}"
print(str.format(26))
print(".....Intiger.....")
print("{}".format(10)) 
print("{} {}".format(10,20))
print("{0}".format(10))
print("{0} {1}".format(10,20))
print("{1} {0}".format(10,20))
print("{num1}".format(num1=10))
print("{num1} {num2}".format(num1=10,num2=20))
print("{num2} {num1}".format(num1=10,num2=20))
print(".....Float.....")
print("{}".format(10.56))
print("{} {}".format(10.56,20.42))
print("{0}".format(10.56))
print("{0} {1}".format(10.56,20.42))
print("{1} {0}".format(10.56,20.42))
print("{num1} {num2}".format(num1=10.56,num2=20.42))
print("{num2} {num1}".format(num1=10.56,num2=20.42))
print(".....String......")
print("{}".format("Prakash"))
print("{} {}".format("Prakash","Anpat"))
print("{0}".format("Prakash"))
print("{0} {1}".format("Prakash","Anpat"))
print("{1} {0}".format("Prakash","Anpat"))
print("{num1} {num2}".format(num1="Prakash",num2="Anpat"))
print("{num2} {num1}".format(num1="Prakash",num2="Anpat"))
print("Intiger & String")
a="My name is {} & my age is {}".format("Prakash",26)
print(a)
b="My name is {} & my  age is {}"
print(b.format("Prakash",26))
print("{} {}".format(26,"Prakash"))
print("{0} {1}".format(26,"Prakash"))
print("{1} {0}".format(26,"Prakash"))
print("{I1} {S1}".format(I1=26,S1="Prakash"))
print("{S1} {I1}".format(I1=26,S1="Prakash"))